### PR TITLE
kalabox/kalabox#287 better hipache static files

### PR DESCRIPTION
**Pull request by reynoldsalec**
This commit should satisfy kalabox/kalabox#287.

Note that the solution is a bit heavy-handed (it pulls over all the sass stuff from the Kalamuna site), so doing a pass through and getting rid of all that cruft would be beneficial.

### CODE REVIEW

**Comment by reynoldsalec** [comment]
@pirog if you can ok this, since it's a change that doesn't threaten the integrity of the hipache proxy I think it'd be easiest to just merge it in and get the updated build to test it all out. AKA "do it live".

**Comment by pirog** [comment]
@reynoldsalec yeah we should def strip this down so its only the needed production assets. Do you want to do that as part of this issue or have me merge this and open a new ticket for that one?

**Comment by pirog** [comment]
bump @reynoldsalec

**Comment by pirog** [comment]
Nice @reynoldsalec!

The only thought i have here is to consolidate the commit and force push so we dont have to download the extra commit history when we build this image.

**Pull request merged**
